# Default values for ibm-cp4d-watson-machine-learning.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
metadata:
  name: wml-cr     # This is the recommended name, but you can change it
spec:
  docker_registry_prefix: cp.icr.io/cp/cpd
  ignoreForMaintenance: "false"
  scaleConfig: medium    #This value can be set to small or medium
  license:
    accept: "true"
    license: Enterprise   # Specify the license you purchased
  storageClass: managed-nfs-storage          #if you use a different storage class, replace it with the appropriate storage class
