{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ibm-cp4d-watson-studio-instance.serviceAccountName" . }}
  labels:
    {{- include "ibm-cp4d-watson-studio-instance.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
